logging:
  pattern:
    console: "%d{ISO8601} type=%highlight(%level) thread=%magenta(%thread) class=%cyan(%class{0}) method=%green(%method) line=%yellow(%line) %m%n%xThrowable"

server:
  port: 9999

spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:rinha}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:123}
